### ISSUE TITLE
Capter 03: Code Review

### ISSUE THREAD

**Issue by sanklamm** [zuff-digital/brave-clojure#1]
## General
You could make a Clojure project out of this repo instead of a loose collection of files ;)

## ex02/03
I would name your functions `add-100` and `dec-7`.

## ex05/06
Good idea of using the maps feature to just add more information (`:number`). Problem is, the function to hit a body part from before now does not work anymore. You are essentially violating the contract of existing functions.  

All in all, good stuff. Good names and concise.

**Comment by zuff-digital** [comment]
Ah, you're right about this breaking the hitting function, failed to consider that in my haste. 
I appreciate you taking the time to review!
